--ESTRUCTURA DE BLOQUE PL/SQL 

DECLARE

-- ES UNA SECCIÓN OPCIONAL Y COMIENZA CON LA PALABRA CLAVE "DECLARE". 
-- SE UTILIZA PARA DECLARAR LAS VARIABLES, CONSTANTES, CURSORES DE REGISTROS, ETC.

BEGIN

-- LA SECCIÓN DE EJECUCIÓN COMIENZA CON LA PALABRA CLAVE "BEGIN" Y TERMINA CON LA PALABRA CLAVE "END". 
-- ES UNA SECCIÓN OBLIGATORIA. 
-- SE UTILIZA PARA ESCRIBIR EL CÓDIGO LÓGICO DEL PROGRAMA.
-- NOTA: LA SECCIÓN DE EJECUCIÓN DEBE TENER UNA DECLARACIÓN

 EXCEPTION

 -- LA SECCIÓN DE EXCEPCION COMIENZA CON LA PALABRA CLAVE "EXCEPTION". 
 -- ES UNA SECCIÓN OPCIONAL. 
 -- SE UTILIZA PARA MANEJAR LAS EXCEPCIONES QUE OCURREN EN LA SECCIÓN DE EJECUCIÓN.
    
END;