-- SELECT INTO

-- SE UTILIZA PARA ASIGNAR LOS RESULTADOS DE UNA CONSULTA SQL DIRECTAMENTE A VARIABLES O REGISTROS DENTRO DE UN BLOQUE DE CÓDIGO PL/SQL.



-- SINTAXIS:

/*


SELECT COLUMNA1, COLUMNA2, ...
INTO VARIABLE1, VARIABLE2, ...
FROM TABLA
WHERE CONDICIÓN;


*/


-- REGAS IMPORTANTES:

-- 1. DEBE DEVOLVER EXACTAMENTE UN SOLO REGISTRO, SI DEVUELVE MÁS DE UNO, DA ERROR "TOO MANY ROWS".
-- 2. SI NO DEVUELVE NINGÚN REGISTRO, DA ERROR "NO DATA FOUND".
-- 3. LAS VARIABLES DEBEN SER DEL MISMO TIPO DE DATOS QUE LAS COLUMNAS SELECCIONADAS.






-- TABLA PARA EJEMPLOS:


CREATE TABLE EMPLEADOS (
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    SALARIO NUMBER,
    DEPARTAMENTO_ID NUMBER
);


-- INSERCCIONES PARA EJEMPLOS:


INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, SALARIO, DEPARTAMENTO_ID) VALUES (101, 'Juan Pérez', 3000, 10);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, SALARIO, DEPARTAMENTO_ID) VALUES (102, 'María López', 3500, 20);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, SALARIO, DEPARTAMENTO_ID) VALUES (103, 'Carlos García', 4000, 10);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, SALARIO, DEPARTAMENTO_ID) VALUES (104, 'Ana Sánchez', 2800, 30);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, SALARIO, DEPARTAMENTO_ID) VALUES (105, 'Luis Rodríguez', 3200, 20);




-- EJEMPLO 1:


DECLARE

   V_NOMBRE EMPLEADOS.NOMBRE%TYPE;
   V_SALARIO EMPLEADOS.SALARIO%TYPE;

BEGIN

   SELECT NOMBRE, SALARIO   -- SE OBTIENE EL NOMBRE Y SALARIO DEL EMPLEADO CON ID = 101
   INTO V_NOMBRE, V_SALARIO
   FROM EMPLEADOS
   WHERE ID_EMPLEADO = 101;
   
   DBMS_OUTPUT.PUT_LINE('Nombre: ' || V_NOMBRE);
   DBMS_OUTPUT.PUT_LINE('Salario: ' || V_SALARIO);

END;





-- EJEMPLO 2:


DECLARE

   V_NOMBRE EMPLEADOS.NOMBRE%TYPE;
   V_SALARIO EMPLEADOS.SALARIO%TYPE;

BEGIN

   SELECT NOMBRE, SALARIO    -- INTENTA OBTENER LOS DATOS DEL EMPLEADO CON ID = 999 (NO EXISTE)
   INTO V_NOMBRE, V_SALARIO
   FROM EMPLEADOS
   WHERE ID_EMPLEADO = 999;
   

   DBMS_OUTPUT.PUT_LINE('Nombre: ' || V_NOMBRE);
   DBMS_OUTPUT.PUT_LINE('Salario: ' || V_SALARIO);

EXCEPTION


   WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('Error: No se encontró el empleado.');

   WHEN TOO_MANY_ROWS THEN
      DBMS_OUTPUT.PUT_LINE('Error: La consulta devolvió múltiples registros.');
END;



-- EJEMPLO 3

