-- FUNCION


-- UNA FUNCIÓN EN PL/SQL ES UN BLOQUE DE CÓDIGO QUE REALIZA UNA TAREA Y DEVUELVE UN VALOR. 
-- ES SIMILAR A UN PROCEDIMIENTO, PERO SIEMPRE DEVUELVE UN RESULTADO.



-- SINTAXIS:

/*

CREATE OR REPLACE FUNCTION NOMBRE_FUNCION (PARAMETRO1 TIPO, PARAMETRO2 TIPO)  

RETURN TIPO AS  

   VARIABLE TIPO;   -- DECLARACIÓN DE VARIABLES


BEGIN  

   -- LÓGICA DE LA FUNCIÓN

   RETURN VALOR;  

END;


*/





-- EJEMPLO 1:



CREATE OR REPLACE FUNCTION SUMA_DOS_NUMEROS(A NUMBER, B NUMBER) 
 
RETURN NUMBER AS
  
   V_RESULTADO NUMBER;  

BEGIN  

   V_RESULTADO := A + B; 
 
   RETURN V_RESULTADO;  
END;


-- LLAMAR A LA FUNCIÓN PARA EJECUTAR LA FUNCION:

SELECT SUMA_DOS_NUMEROS(5, 10) FROM DUAL;  -- "DUAL" ES UNA TABLA TEMPORAL QUE VIENE POR DEFECTO EN ORACLE.
					   -- SE UTILIZA PARA EVALUAR EXPRESIONES, EJECUTAR FUNCIONES O DEVOLVER VALORES CONSTANTES SIN NECESIDAD DE UNA TABLA REAL.






-- ELIMINAR UNA FUNCION

-- SINTAXIS: DROP FUNCTION NOMBRE_FUNCION;




 -- EJEMPLO DEL CASO ANTERIOR

DROP FUNCTION SUMA_DOS_NUMEROS;








-- EJEMPLO 2:

-- FUNCIÓN QUE IMPRIME SIN "SELECT"


CREATE OR REPLACE FUNCTION SALUDO(NOMBRE VARCHAR2)

RETURN VARCHAR2 AS

BEGIN

   DBMS_OUTPUT.PUT_LINE('¡HOLA, ' || NOMBRE || '! BIENVENIDO A PL/SQL');

   RETURN 'SALUDO ENVIADO';
END;




-- LLAMAR A LA FUNCIÓN PARA EJECUTAR LA FUNCION:

DECLARE

   MENSAJE VARCHAR2(50);

BEGIN

   MENSAJE := SALUDO('ENRIQUE');

END;







-- EJEMPLO 3:

-- FUNCIÓN QUE ACCEDE A UNA TABLA



-- TABLA:


CREATE TABLE EMPLEADOS (
   EMPLEADO_ID NUMBER PRIMARY KEY,    
   NOMBRE VARCHAR2(100),           
   CARGO VARCHAR2(50),             
   SALARIO NUMBER(10,2)           
);



-- DATOS:

INSERT INTO EMPLEADOS (EMPLEADO_ID, NOMBRE, CARGO, SALARIO) VALUES (101, 'CARLOS RAMÍREZ', 'ANALISTA', 2500.50);
INSERT INTO EMPLEADOS (EMPLEADO_ID, NOMBRE, CARGO, SALARIO) VALUES (102, 'ANA PÉREZ', 'DESARROLLADORA', 3200.75);
INSERT INTO EMPLEADOS (EMPLEADO_ID, NOMBRE, CARGO, SALARIO) VALUES (103, 'JUAN GÓMEZ', 'GERENTE', 5000.00);





-- FUNCION:



CREATE OR REPLACE FUNCTION OBTENER_SALARIO(ID_EMPLEADO NUMBER)

RETURN NUMBER AS

   SALARIO NUMBER;

BEGIN

   SELECT SALARIO INTO SALARIO FROM EMPLEADOS WHERE EMPLEADO_ID = ID_EMPLEADO;

   RETURN SALARIO;
END;


-- LLAMAR A LA FUNCIÓN PARA EJECUTARLA:


DECLARE
	
   V_SALARIO NUMBER;

BEGIN
	
   V_SALARIO := OBTENER_SALARIO(101);

   DBMS_OUTPUT.PUT_LINE('El salario del empleado con ID 101 es: ' || V_SALARIO);

END;
