--PROCEDIMIENTO

-- UN PROCEDIMIENTO ES UN BLOQUE DE CÓDIGO QUE REALIZA UNA ACCIÓN ESPECÍFICA, PERO NO DEVUELVE UN VALOR. SE PUEDE USAR PARA ENCAPSULAR Y REUTILIZAR LÓGICA,
-- HACER TAREAS COMO INSERTAR, ACTUALIZAR, O BORRAR REGISTROS EN UNA BASE DE DATOS, ENTRE OTRAS. 

-- LOS PARÁMETROS PUEDE SER DE TIPO 'IN' (ENTRADA), 'OUT' (SALIDA) O 'IN OUT' (ENTRADA Y SALIDA). 
-- LOS PROCEDIMIENTOS NO DEVUELVEN VALORES DIRECTAMENTE (AL CONTRARIO DE LAS FUNCIONES).

CREATE PROCEDURE NOMBRE_DEL_PROCEDIMIENTO (PARAMETRO1 IN TIPO, PARAMETRO2 OUT TIPO, ...)

IS
   -- DECLARACIÓN DE VARIABLES
   -- AQUÍ SE PUEDEN DECLARAR VARIABLES LOCALES QUE SERÁN USADAS DENTRO DEL PROCEDIMIENTO.

BEGIN

   -- CÓDIGO DE EJECUCIÓN
   -- SENTENCIAS SQL Y PL/SQL
   -- AQUÍ SE EJECUTAN LAS ACCIONES QUE DESEA REALIZAR EL PROCEDIMIENTO, 
   -- COMO CONSULTAS, INSERCIÓN, ACTUALIZACIÓN, ETC.

EXCEPTION

   -- MANEJO DE EXCEPCIONES
   -- AQUÍ SE PUEDEN CAPTURAR ERRORES O EXCEPCIONES QUE SE PUEDAN PRESENTAR DURANTE LA EJECUCIÓN.

END;