-- CURSORES


-- UN CURSOR SE UTILIZA PARA MANEJAR EL JUEGO DE RESULTADOS DE UNA SENTENCIA SELECT.







-- TIPOS DE CURSORES:



-- IMPLICITOS: ORACLE LOS CREA INTERNAMENTE CUANDO EJECUTAMOS UNA SENTENCIA SQL. (SON INACCESIBLES)



-- EXPLICITOS: DECLARADOS POR EL PROGRAMADOR, SIRVEN PARA RECUPERAR VARIAS FILAS DE LA BASE DE DATOS.







-- ATRIBUTOS:


-- LOS CURSORES TIENEN ATRIBUTOS QUE PERMITEN MONITOREAR SU ESTADO.



-- "SQL%FOUND": ATRIBUTO BOOLEANO QUE SE EVALÚA COMO '"TRUE" SI LA SENTENCIA SQL MÁS RECIENTE AFECTA, COMO MÍNIMO, A UNA FILA.



-- "SQL%NOTFOUND": ATRIBUTO BOOLEANO QUE SE EVALÚA COMO "TRUE" SI LA SENTENCIA SQL MÁS RECIENTE NO AFECTA A NINGUNA FILA.



-- "SQL%ROWCOUNT": VALOR ENTERO QUE REPRESENTA EL NÚMERO DE FILAS AFECTADAS POR LA SENTENCIA SQL MÁS RECIENTE.








-- TABLA PARA EJEMPLO:





CREATE TABLE EMPLEADOS_EB (
    ID_EMPLEADO INT PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DEPARTAMENTO VARCHAR2(50),
    SALARIO DECIMAL(10, 2)
);


-- DATOS PARA EJEMPLO:


INSERT INTO EMPLEADOS_EB  (ID_EMPLEADO, NOMBRE, DEPARTAMENTO, SALARIO)
VALUES (1, 'JUAN PÉREZ', 'VENTAS', 3500.00);

INSERT INTO EMPLEADOS_EB  (ID_EMPLEADO, NOMBRE, DEPARTAMENTO, SALARIO)
VALUES (2, 'MARÍA GÓMEZ', 'VENTAS', 4000.00);

INSERT INTO EMPLEADOS_EB  (ID_EMPLEADO, NOMBRE, DEPARTAMENTO, SALARIO)
VALUES (3, 'CARLOS LÓPEZ', 'TI', 4500.00);

INSERT INTO EMPLEADOS_EB  (ID_EMPLEADO, NOMBRE, DEPARTAMENTO, SALARIO)
VALUES (4, 'LAURA MARTÍNEZ', 'VENTAS', 3800.00);

INSERT INTO EMPLEADOS_EB  (ID_EMPLEADO, NOMBRE, DEPARTAMENTO, SALARIO)
VALUES (5, 'PABLO FERNÁNDEZ', 'TI', 4700.00);






-- EJEMPLO CURSOR IMPLICITO:


BEGIN

    UPDATE EMPLEADOS_EB  
    SET SALARIO = SALARIO * 1.10  
    WHERE DEPARTAMENTO = 'VENTAS';

    IF SQL%FOUND THEN  

        DBMS_OUTPUT.PUT_LINE('SE ACTUALIZARON ' || SQL%ROWCOUNT || ' FILAS.');
        
    END IF;
END;




-- EJEMPLO CURSOR EXPLICITO:

DECLARE

    CURSOR CURSOR_EMPLEADOS IS  
    SELECT NOMBRE 
    FROM EMPLEADOS_EB 
    WHERE DEPARTAMENTO = 'VENTAS';

    V_NOMBRE EMPLEADOS_EB.NOMBRE%TYPE;

BEGIN

    OPEN CURSOR_EMPLEADOS; -- ABRIR CURSOR

    LOOP --RECORRE TODAS LAS FILAS DEL CURSOR

        FETCH CURSOR_EMPLEADOS INTO V_NOMBRE;  -- RECUPERAMOS CADA NOMBRE Y LO GUARDAMOS EN "V_NOMBRE"
        EXIT WHEN CURSOR_EMPLEADOS%NOTFOUND;   -- SALE SI NO HAY MAS FILAS

        DBMS_OUTPUT.PUT_LINE('Empleado: ' || V_NOMBRE);

    END LOOP;

    CLOSE CURSOR_EMPLEADOS; -- CERRAR CURSOR

END;










-- |||||||||||||||||||||||||||||||||||||||||||||||||

--  NO EXISTEN CURSORES IMPLÍCITOS CON PARÁMETROS.

-- |||||||||||||||||||||||||||||||||||||||||||||||||






-- EJEMPLO CURSORES EXPLÍCITOS CON PARÁMETROS:




DECLARE


    CURSOR CURSOR_EMPLEADOS(P_DEPARTAMENTO VARCHAR2) IS
    SELECT NOMBRE, SALARIO
    FROM EMPLEADOS_EB
    WHERE DEPARTAMENTO = P_DEPARTAMENTO;

    V_NOMBRE EMPLEADOS_EB.NOMBRE%TYPE;
    V_SALARIO EMPLEADOS_EB.SALARIO%TYPE;

BEGIN

    OPEN CURSOR_EMPLEADOS('VENTAS');


    LOOP

        FETCH CURSOR_EMPLEADOS INTO V_NOMBRE, V_SALARIO;
        EXIT WHEN CURSOR_EMPLEADOS%NOTFOUND;


        DBMS_OUTPUT.PUT_LINE('Empleado: ' || V_NOMBRE || ' - Salario: ' || V_SALARIO);

    END LOOP;


    CLOSE CURSOR_EMPLEADOS;

END;




























