-- VARIABLES


-- CARACTERISTICAS A LA HORA DE PONER UN NOMBE A UNA VARIABLE:

-- 1. DEBE EMPEZAR POR UNA LETRA.  
-- 2. PUEDE INCLUIR LETRAS Y NÚMEROS.  
-- 3. PUEDE INCLUIR CARACTERES ESPECIALES (COMO $, _ Y #)  
-- 4. NO DEBE CONTENER MÁS DE 30 CARACTERES.  
-- 5. NO DEBE INCLUIR PALABRAS RESERVADAS.  




-- SINTAXIS:

-- NOMBRE_VARIABLE TIPO_DE_DATO := VALOR_INICIAL;

-- EL VALOR INICIAL ES OPCIONAL.






-- TIPOS DE VARIABLES:



DECLARE


   -- CADENAS DE TEXTO
   V_NOMBRE VARCHAR2(50) := 'JUAN PÉREZ';  
   V_APELLIDO CHAR(10) := 'GÓMEZ';  


-- ":=" EN PL/SQL SE UTILIZA PARA ASIGNAR UN VALOR A UNA VARIABLE.



   -- NÚMEROS
   V_EDAD NUMBER(3) := 25;  
   V_SALARIO NUMBER(10,2) := 2500.75;  



   -- BOOLEANOS
   V_ES_ACTIVO BOOLEAN := TRUE;  


   -- FECHAS
   V_FECHA_NACIMIENTO DATE := TO_DATE('1998-05-10', 'YYYY-MM-DD');  
   V_FECHA_ACTUAL DATE := SYSDATE;  




   -- TIPOS DE DATOS BASADOS EN TABLAS 



   -- GRANDES VOLÚMENES DE TEXTO
   V_COMENTARIOS CLOB := 'ESTE ES UN TEXTO LARGO...';  



   -- CONSTANTES (SU VALOR NO PUEDE CAMBIAR DESPUÉS DE SER ASIGNADO)
   PI CONSTANT NUMBER := 3.1416; 


BEGIN


-- IMPRIMIR LOS VALORES:


-- "DBMS_OUTPUT.PUT_LINE" EN PL/SQL SE USA PARA MOSTRAR MENSAJES O VALORES EN LA CONSOLA.

   
-- SINTAXIS:

-- DBMS_OUTPUT.PUT_LINE('TEXTO O VARIABLE');


   DBMS_OUTPUT.PUT_LINE('HOLA, MUNDO EN PL/SQL');
   DBMS_OUTPUT.PUT_LINE('NOMBRE: ' || V_NOMBRE);
   DBMS_OUTPUT.PUT_LINE('APELLIDO: ' || V_APELLIDO);
   DBMS_OUTPUT.PUT_LINE('EDAD: ' || V_EDAD);
   DBMS_OUTPUT.PUT_LINE('SALARIO: ' || V_SALARIO);
   DBMS_OUTPUT.PUT_LINE('ESTÁ ACTIVO: ' || CASE WHEN V_ES_ACTIVO THEN 'SÍ' ELSE 'NO' END);
   DBMS_OUTPUT.PUT_LINE('FECHA NACIMIENTO: ' || TO_CHAR(V_FECHA_NACIMIENTO, 'DD-MON-YYYY'));
   DBMS_OUTPUT.PUT_LINE('FECHA ACTUAL: ' || TO_CHAR(V_FECHA_ACTUAL, 'DD-MON-YYYY'));
   DBMS_OUTPUT.PUT_LINE('CONSTANTE PI: ' || PI);
   DBMS_OUTPUT.PUT_LINE('COMENTARIOS: ' || V_COMENTARIOS);








END;


