-- CONVERSION DE DATOS

-- LA CONVERSIÓN DE DATOS SE REFIERE AL PROCESO DE CAMBIAR UN VALOR DE UN TIPO DE DATO A OTRO.


-- IMPLICITA 

-- LA CONVERSIÓN IMPLÍCITA OCURRE AUTOMÁTICAMENTE CUANDO PL/SQL PUEDE CONVERTIR UN TIPO DE DATO A OTRO SIN QUE SEA NECESARIO ESPECIFICARLO EXPLÍCITAMENTE. 
-- ESTO SUELE SUCEDER CUANDO SE ASIGNAN VALORES ENTRE VARIABLES DE TIPOS COMPATIBLES.

DECLARE

  V_NUMERO NUMBER := 1234;
  V_TEXTO VARCHAR2(50);

BEGIN

  V_TEXTO := V_NUMERO; -- CONVIERTE EL NUMBER EN VARCHAR2.

  DBMS_OUTPUT.PUT_LINE('EL NÚMERO CONVERTIDO A TEXTO ES: ' || V_TEXTO);

END;

-- CONVERSION EXPLICITA

-- LA CONVERSIÓN EXPLÍCITA SE REFIERE AL PROCESO EN EL QUE EL PROGRAMADOR ESPECIFICA EXPLÍCITAMENTE CÓMO CONVERTIR UN VALOR DE UN TIPO DE DATO A OTRO. 
-- SE UTILIZAN FUNCIONES PARA REALIZAR LA CONVERSIÓN.

-- ESTO SE UTILIZA CUANDO LOS TIPOS DE DATOS NO SON DIRECTAMENTE COMPATIBLES O CUANDO SE NECESITA UN CONTROL MÁS PRECISO SOBRE LA CONVERSIÓN.

-- LISTA DE FUNCIONES:

    -- TO_NUMBER: CONVIERTE UN VALOR A TIPO NUMBER.
    -- TO_CHAR: CONVIERTE UN VALOR A TIPO VARCHAR2.
    -- TO_DATE: CONVIERTE UN VALOR A TIPO DATE.
    -- TO_TIMESTAMP: CONVIERTE UN VALOR A TIPO TIMESTAMP.
    -- TO_CLOB: CONVIERTE UN VALOR A TIPO CLOB (CHARACTER LARGE OBJECT).
    -- TO_BLOB: CONVIERTE UN VALOR A TIPO BLOB (BINARY LARGE OBJECT).

 -- EJEMPLO TO_NUMBER

 DECLARE

  V_TEXTO VARCHAR2(50) := '1234';
  V_NUMERO NUMBER;

BEGIN

  
  V_NUMERO := TO_NUMBER(V_TEXTO); -- PASA DE VARCHAR2 A NUMBER.

  DBMS_OUTPUT.PUT_LINE('EL NÚMERO ES: ' || V_NUMERO);

END;

-- EJEMPLO TO_DATE

DECLARE

V_DATE_CHAR VARCHAR2(100) := '02 02 2024';
V_DATE DATE;

BEGIN

V_DATE := TO_DATE(V_DATE_CHAR,'DD MM YYYY'); -- PASA DE VARCHAR2 A DATE

DBMS_OUTPUT.PUT_LINE('FECHA:' || V_DATE);

END;

