--  FETCH FIRST

-- ES UNA CLÁUSULA DE SQL QUE TE PERMITE LIMITAR EL NÚMERO DE FILAS QUE DEVUELVE UNA CONSULTA. 
-- SE USA PARA OBTENER SOLO UN NÚMERO ESPECÍFICO DE FILAS, POR LO GENERAL LA PRIMERA FILA DE LOS RESULTADOS SEGÚN UN ORDEN DADO.



--SINTAXIS:


/*


SELECT columnas
FROM tabla
ORDER BY columna
FETCH FIRST N ROWS ONLY;  -- "N" ES EL NÚMERO DE FILAS QUE DESEAS RECUPERAR.


*/




-- ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

-- TABLA EJEMPLO:


CREATE TABLE ACTORES (
    ID_ACTOR NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    FECHA_NACIMIENTO DATE
);



INSERT INTO ACTORES (ID_ACTOR, NOMBRE, FECHA_NACIMIENTO) VALUES (1, 'JUAN PÉREZ', TO_DATE('1990-01-01', 'YYYY-MM-DD'));
INSERT INTO ACTORES (ID_ACTOR, NOMBRE, FECHA_NACIMIENTO) VALUES (2, 'MARÍA LÓPEZ', TO_DATE('1995-03-15', 'YYYY-MM-DD'));
INSERT INTO ACTORES (ID_ACTOR, NOMBRE, FECHA_NACIMIENTO) VALUES (3, 'PEDRO GÓMEZ', TO_DATE('2000-05-20', 'YYYY-MM-DD'));
INSERT INTO ACTORES (ID_ACTOR, NOMBRE, FECHA_NACIMIENTO) VALUES (4, 'LUISA FERNÁNDEZ', TO_DATE('1992-07-10', 'YYYY-MM-DD'));


-- ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||



-- EJEMPLO I:


SELECT NOMBRE, FECHA_NACIMIENTO
FROM ACTORES
ORDER BY FECHA_NACIMIENTO DESC  
FETCH FIRST 1 ROW ONLY;          


-- ////////////////////////////////////////////////////////////////


-- EJEMPLO II:

SELECT NOMBRE, FECHA_NACIMIENTO
FROM ACTORES
ORDER BY FECHA_NACIMIENTO DESC  
FETCH FIRST 3 ROWS ONLY;        -- SOLO LAS PRIMERAS 3 LINEAS



