-- BLOQUE ANONIMO


-- UN BLOQUE ANÓNIMO ES UN FRAGMENTO DE CÓDIGO QUE NO TIENE NOMBRE, LO QUE SIGNIFICA QUE NO SE ALMACENA EN LA BASE DE DATOS COMO UN PROCEDIMIENTO, FUNCIÓN O PAQUETE.

-- SE UTILIZA PRINCIPALMENTE PARA EJECUTAR CÓDIGO EN UNA SESIÓN SIN NECESIDAD DE DECLARAR UNA ESTRUCTURA PERMANENTE EN LA BASE DE DATOS.



SINTAXIS:


DECLARATIVO (OPCIONAL) -- SIRVE PARA DECLARAR VARIABLES Y TIPOS DE DATOS

EJECUTABLE -- ES DONDE SE EJECUTA EL CODIGO

EXCEPCIONES (OPCIONAL) -- MANEJA ERRORES QUE SE HAN PRODUCIDO DURANTE LA EJECUCION



-- EJEMPLO 1:


DECLARE

   NOMBRE VARCHAR2(50);

BEGIN

   NOMBRE := 'Enrique';


   DBMS_OUTPUT.PUT_LINE('Hola, ' || NOMBRE);  -- IMPRIMIMOS EL VALOR EN LA CONSOLA

END;






-- EJEMPLO 2:



DECLARE

   NUMERO1 NUMBER := 10;
   NUMERO2 NUMBER := 0;  -- ESTE VALOR GENERARÁ UN ERROR DE DIVISIÓN POR CERO

   RESULTADO NUMBER;


BEGIN


   RESULTADO := NUMERO1 / NUMERO2;

   DBMS_OUTPUT.PUT_LINE('El resultado es: ' || RESULTADO);


EXCEPTION

   
   WHEN ZERO_DIVIDE THEN -- SI OCURRE UN ERROR DE DIVISIÓN POR CERO

      DBMS_OUTPUT.PUT_LINE('Error: No se puede dividir entre cero.');


   WHEN OTHERS THEN -- SI OCURRE CUALQUIER OTRO ERROR

      DBMS_OUTPUT.PUT_LINE('Error desconocido: ' || SQLERRM);

END;





-- EJEMPLO 3:




-- TABLA:


CREATE TABLE ACTORES_TEMP (
    ACTOR_ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    NACIONALIDAD VARCHAR2(50)
);


-- DATOS:


INSERT INTO ACTORES_TEMP (ACTOR_ID, NOMBRE, NACIONALIDAD) VALUES (1, 'Vin Gasoil', 'Estadounidense');

INSERT INTO ACTORES_TEMP (ACTOR_ID, NOMBRE, NACIONALIDAD) VALUES (2, 'Scarlett Johansson', 'Estadounidense');



-- BLOQUE ANONIMO:


DECLARE

    V_ID NUMBER;
    V_NOMBRE VARCHAR2(50);
    V_NACIONALIDAD VARCHAR2(50);

BEGIN

    SELECT ACTOR_ID, NOMBRE, NACIONALIDAD INTO V_ID, V_NOMBRE, V_NACIONALIDAD
    FROM ACTORES_TEMP
    WHERE NOMBRE = 'Vin Gasoil';

    DBMS_OUTPUT.PUT_LINE('El actor ' || V_NOMBRE || ' con ID ' || V_ID || ' es de nacionalidad ' || V_NACIONALIDAD || '.');

END;


